// <auto-generated />
namespace Parliament.Interact.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedalinkerclassasrequiredbythenewcontentspecificitems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedalinkerclassasrequiredbythenewcontentspecificitems));
        
        string IMigrationMetadata.Id
        {
            get { return "201603290929437_Added a linker class as required by the new content specific items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
