// <auto-generated />
namespace Parliament.Interact.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedactionitemstotable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedactionitemstotable));
        
        string IMigrationMetadata.Id
        {
            get { return "201603221516092_added action items to table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
